import LocalizedStrings from "react-localization";

const strings = new LocalizedStrings({
  en: {
    NavHome: "Home",
    NavAbout: "About Us",
    NavAnno: "Announcements",
    NavEver: "Evergreen",
    NavGallery: "Gallery",
    NavContact: "Contact",
    homeTitle: "Welcome to ECCCA",
    homeSubTitle: "Essex County Chinese Canadian Association",
    homeFund: "Our Association Is Funded By",
    homeSecondTitle: "Welcome to ECCCA",
    homeSecondSubTitle: "Essex County Chinese Canadian Association",
    // homeSecondText: textEN[0],
    // homeSecondSecText: textEN[1],
    // aboutText: textEN[2],
    // aboutText2: textEN[3],
    // aboutText3: textEN[4],
    homeSecondText:
      "Established in 1976, the Essex County Chinese Canadian Association promotes understanding and partnership between Chinese Canadians and the broader Essex County community. The ECCCA has provided many educational, cultural, recreational and social programs such as language, dance, choir, tai chi, cooking, and fitness classes. The ECCCA's Evergreen Centre provides information and social support to Chinese seniors to reduce their isolation and improve their well-being and quality of life.",
    homeSecondSecText:
      "The ECCCA is an active partner in community-wide events and activities that include: the Carrousel of Nations, Spring and Autumn Festivals, annual Chinese Lunar New Year festivities at the Art Gallery of Windsor (2009-14) and Devonshire Mall (since 2015), Canada Day Parade, Mid-Autumn Festival celebrations, and social outreach to retirement and long-term care homes.",
    aboutTitle: "About Us",
    aboutText:
      "In 1976, responding to the needs of the Chinese community in Windsor, the Essex County Chinese Canadian Association was founded to promote Chinese culture and to help integrate Chinese into mainstream society. Dr. Chosen Lau was one of the founders and the first president of the association. One of the first steps of integration was the introduction of the celebration of Chinese New Year in the oriental tradition. In 1976 the first Annual New Year Banquet was held at the Cleary International Center. Dr. Edward Ng was instrumental in organizing the successful Chinese cabaret in 1980, to promote cultural exchange between the East and West.",
    aboutText2:
      "In January 1982, the first association centre at Church St. was opened by Mayor Bert Weeks. Before that, the executive members would meet in various places – members’ homes or restaurants - to conduct the activities of the association. Subsequently, the centre moved to the Red Cross Building at 1226 Ouellette Ave. and then to the renovated building at 665 Ouellette Ave. Finally in 1990 the current facility at 1420 Tecumseh Rd. East was purchased. Besides the annual Chinese New Year Fundraising Gala, the Essex County Chinese Canadian Association also organizes the annual New Year Party for seniors as a gesture of respect.",
    aboutText3:
      "Every year since it was established, the association has participated in the Canada Day Parade and the annual Carrousel of the Nations organized by the Multicultural Council of Windsor. The association has contributed tremendously to the promotion of Chinese culture in Windsor. The association also provides many other activities such as Chinese literature classes, mandarin classes and tai chi classes and publishes the annual Chinese Business and Professional Directory.",
    aboutBoard: "Board of Directors",
    annoTitle: "Announcement",
    galleryTitle: "Gallery",
    contactInfo: "Contact Info",
    contactAdd: "1420 Tecumseh Road East Windsor, Ontario, N8W 1C1",
    contactEmail: "info@eccca.net",
    contactPhone: "Phone: (519) 252-6621",
    contactUs: "Contact Us",
    formName: "Name",
    formPhone: "Phone",
    formEmail: "Email",
    formMessage: "Message",
    formSend: "Send",
    langTag: "Language",
    aboutPayment: "About Payment",
    etransfer: "We only accept e-transfer.",
    recipientName: "Recipient Name: abccc",
    recipientEmail: "Recipient Email: abc@gmail.com",
    messageRequired: "Message*: For Eccca xxx acitiviy",
    etransNotice: "Auto Deposit is enabled for the recipient above. If you require a security question, please use this:",
    securityQuestion: "Question: ECCCA; Answer: Essex;",
    president:"President",
    vicePresident:"Vice-President",
    treasurer:"Treasurer",
    enSecretary:"English Secretary",
    cnSecretary:"Chinese Secretary",
    directorACE:"Director Art/Culture/Event Planning",
    directorYouth:"Director Youth Program",
    directorPublic:"Director Public Affairs",
    director:"Director"
  },
  ch: {
    NavHome: "首頁",
    NavAbout: "關於我們",
    NavAnno: "公告",
    NavEver: "松柏中心",
    NavGallery: "相薄相冊",
    NavContact: "聯繫我們",
    homeTitle: "歡迎蒞臨ECCCA",
    homeSubTitle: "雅斯郡華人協會",
    homeFund: "我們的協會由以下機構資助",
    homeSecondTitle: "歡迎蒞臨雅斯郡華人協會",
    homeSecondSubTitle: "",
    // homeSecondText: textCN[0],
    // homeSecondSecText: textCN[1],
    // aboutText: textCN[2],
    // aboutText2: textCN[3],
    // aboutText3: textCN[4],
    homeSecondText:
      "雅斯郡華人協會于1976年成立. 協會一直以來推廣中華文化, 了解和溶入主流 社會.積 極 参與社區各項活動促進文化交流. 更為會員設立語言, 電腦, 舞蹈, 歌唱, 太極, 烹飪, 健康舞等多種課程及舉辧有関社會, 生活, 醫療等教育性 知識講座. 華協會的松柏中心特為華裔長者而設. 目的是使長者了解社會, 保健及財務慨 况,多参加集體活動,郊外遠足, 提昇生活質素, 令身心健康. 華協會一直是社區活動的活躍伙伴.",
    homeSecondSecText:
      "参與每年一度多元文化節, 加國國慶遊行 及城市各項文化活動等. 同時每年更舉辧大型慶祝新年籌款晚宴, 會員家 庭賀年宴,慶祝中秋節,高爾夫籌款球賽等. 更與温莎藝術館 (2009-14), Devonshire 商場 (2015 迄今) 舉辧各項文娛活動. 年中協會的合唱團和舞蹈組 常到各大安老院探訪和表演.",
    aboutTitle: "關於我們",
    aboutText:
      "1976年，為了響應溫莎中國群體的號召，雅斯郡華人協會成立了。協會主旨弘揚中華文化與幫助中國群體融入主流社會。劉超信醫生成為了創辦人之一以及第一任協會主席。為了融入主流社會，協會作出了第一步舉動---宣揚慶祝中國新年的東方文化。在同一年，第一屆年度新年宴會在Cleary International Center舉行。1980年，促進東西方文化交流的中國歌舞表演取得圓滿成功，同時Edward吳醫生對此活動組織的成功也功不可沒。",
    aboutText2:
      "1982年1月，第一個協會中心在市長Bert Weeks的帶領下開業。在此之前，成員會在不同的地點（會員家裡或飯店內）進行內部會議，商討協會活動的細節。後來，協會中心移至1226 Ouellette Ave.的紅十字會樓內，然後移至665 Ouellette Ave.的翻新建築內。最後於1990年，協會選址并購買了位於1420 Tecumseh Rd.的設施。這也即是現時協會中心的所在地。除了每年都會舉辦的中國新年籌款晚會外，雅斯郡華人協會也會舉辦新年派對以表示尊重老年人。",
    aboutText3:
      "由創辦至今以來，協會每年都會參加溫莎多元文化委員會組織的國慶日遊行與Carrousel of the Nations活動。協會於溫莎市對弘揚中華文化作出了巨大貢獻。另一方面，協會推出非常多活動服務成員們，例如中國文學課，國語課，太極課。同時，每年協會都會印刷並出版本地號碼簿。",
    aboutBoard: "幹事名單",
    annoTitle: "公告",
    galleryTitle: "相薄",
    contactInfo: "聯繫訊息",
    contactAdd: "1420 Tecumseh Road East Windsor, Ontario, N8W 1C1",
    contactEmail: "info@eccca.net",
    contactPhone: "電話: (519) 252-6621",
    contactUs: "聯繫我們",
    formName: "姓名",
    formPhone: "電話",
    formEmail: "電子郵件",
    formMessage: "您要說的：",
    formSend: "發送",
    langTag: "語言",
    aboutPayment: "關於支付",
    etransfer: "我們現只接受e-transfer，如有不便，非常抱歉。",
    recipientName: "接收對象名字: abccc",
    recipientEmail: "接收對象email: abc@gmail.com",
    messageRequired: "備註*： 為Eccca組織的xxx活動支付",
    etransNotice: "自動收取功能已啓用。若需要填寫安全問題，請填寫一下內容：",
    securityQuestion: "安全問題: ECCCA; 安全密鑰: Essex;",
    president:"會長",
    vicePresident:"副會長",
    treasurer:"財政",
    enSecretary:"英文袐書",
    cnSecretary:"中文袐書",
    directorACE:"幹事文藝項目策劃",
    directorYouth:"幹事青年活動",
    directorPublic:"幹事公共関係",
    director:"幹事"
  }
});

export { strings };
